-keepattributes Signature
-ignorewarnings
-dontwarn com.sunmi.paylib.R$string
-keep class net.kazang.pegasus.** { *; }
-keep class com.google.gson.** { *; }
-keep class com.google.gson.reflect.TypeToken { *; }
-keep class * extends com.google.gson.reflect.TypeToken